data_dir: /media/chris/M2/2-Processed_Data/

feature_sets:
  - Audio-Librosa_win
  - Video-OpenFace_win
  - Annotation-Turns_win

sessions:
  - 1
  - 2
  - 3
  - 5
  - 6
  # - 7
  # - 8
  # - 9
  # - 10
  # - 11
  # - 12
  # - 13
  # # - 14
  # - 15
  # - 16
  # - 17
  # # - 18
  # # - 19
  # - 21
  # - 22
  # - 23
  # - 24
  # - 25
  # - 26
  # - 27

positions:
  - left
  - right
  - center

feature_files:
  Audio-Librosa_win:
    - audio_features.csv
  Video-OpenFace_win:
    - left.csv
    - center.csv
    - right.csv
  Annotation-Turns_win:
    - turns.csv

features:
  Audio-Librosa_win:
    - MFCC_0_mean
    - MFCC_1_mean
    - MFCC_2_mean
    - MFCC_3_mean
    - MFCC_4_mean
    - MFCC_6_mean
    - MFCC_7_mean
    - MFCC_8_mean
    - MFCC_9_mean
    - MFCC_10_mean
    - MFCC_11_mean
    - MFCC_12_mean
    - MFCC_13_mean
    - MFCC_14_mean
    - MFCC_15_mean
    - MFCC_16_mean
    - MFCC_17_mean
    - MFCC_18_mean
    - MFCC_19_mean
    - Chroma_0_mean
    - Chroma_2_mean
    - Chroma_4_mean
    - Chroma_6_mean
    - Chroma_8_mean
    - Chroma_9_mean
    - Chroma_10_mean
    - Mel_Spect_0_mean
    - Mel_Spect_2_mean
    - Mel_Spect_3_mean
    - Mel_Spect_5_mean
    - Mel_Spect_6_mean
    - Mel_Spect_96_mean
    - Mel_Spect_124_mean
    - Mel_Spect_127_mean
    - Spect_Contrast_0_mean
    - Spect_Contrast_1_mean
    - Spect_Contrast_3_mean
    - Spect_Contrast_4_mean
    - Spect_Contrast_6_mean
    - Rolloff_0_mean
    - MFCC_0_var
    - MFCC_2_var
    - MFCC_3_var
    - MFCC_4_var
    - MFCC_5_var
    - MFCC_6_var
    - MFCC_7_var
    - MFCC_8_var
    - MFCC_9_var
    - MFCC_10_var
    - MFCC_11_var
    - MFCC_12_var
    - MFCC_13_var
    - MFCC_14_var
    - MFCC_15_var
    - MFCC_16_var
    - MFCC_17_var
    - MFCC_18_var
    - MFCC_19_var
    - Chroma_0_var
    - Chroma_1_var
    - Chroma_2_var
    - Chroma_3_var
    - Chroma_4_var
    - Chroma_5_var
    - Chroma_6_var
    - Chroma_7_var
    - Chroma_8_var
    - Chroma_9_var
    - Chroma_10_var
    - Chroma_11_var
    - Mel_Spect_0_var
    - Mel_Spect_2_var
    - Mel_Spect_3_var
    - Mel_Spect_4_var
    - Mel_Spect_6_var
    - Mel_Spect_7_var
    - Mel_Spect_8_var
    - Mel_Spect_10_var
    - Mel_Spect_12_var
    - Mel_Spect_14_var
    - Mel_Spect_16_var
    - Mel_Spect_18_var
    - Mel_Spect_20_var
    - Mel_Spect_23_var
    - Mel_Spect_25_var
    - Mel_Spect_27_var
    - Mel_Spect_29_var
    - Mel_Spect_31_var
    - Mel_Spect_36_var
    - Mel_Spect_38_var
    - Mel_Spect_40_var
    - Mel_Spect_42_var
    - Mel_Spect_44_var
    - Mel_Spect_46_var
    - Mel_Spect_51_var
    - Mel_Spect_57_var
    - Mel_Spect_86_var
    - Mel_Spect_91_var
    - Mel_Spect_98_var
    - Spect_Contrast_0_var
    - Spect_Contrast_1_var
    - Spect_Contrast_2_var
    - Spect_Contrast_5_var
    - Spect_Contrast_6_var
    - Rolloff_0_var

  # https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format
  Video-OpenFace_win:
    - AU01_r_mean
    - AU05_r_mean
    - AU06_r_mean
    - AU07_r_mean
    - AU09_r_mean
    - AU10_r_mean
    - AU12_r_mean
    - AU14_r_mean
    - AU15_r_mean
    - AU17_r_mean
    - AU20_r_mean
    - AU23_r_mean
    - AU25_r_mean
    - AU26_r_mean
    - AU45_r_mean
    - gaze_0_x_mean
    - gaze_0_y_mean
    - gaze_0_z_mean
    - pose_Tx_mean
    - pose_Ty_mean
    - pose_Tz_mean
    - pose_Rz_mean
    - x_1_mean
    - x_8_mean
    - x_21_mean
    - x_22_mean
    - x_38_mean
    - x_43_mean
    - x_48_mean
    - x_57_mean
    - x_51_mean
    - x_54_mean
    - x_60_mean
    - x_62_mean
    - x_66_mean
    - y_1_mean
    - y_8_mean
    - y_21_mean
    - y_22_mean
    - y_38_mean
    - y_43_mean
    - y_48_mean
    - y_57_mean
    - y_51_mean
    - y_54_mean
    - y_60_mean
    - y_62_mean
    - y_66_mean
    # - p_scale_mean
    # - p_2_mean
    # - p_3_mean
    # - p_4_mean
    # - p_5_mean
    # - p_6_mean
    # - p_8_mean
    # - p_10_mean
    # - p_12_mean
    # - p_13_mean
    # - p_14_mean
    # - p_15_mean
    # - p_18_mean
    # - p_20_mean
    # - p_21_mean
    # - p_22_mean
    # - p_23_mean
    # - p_24_mean
    # - p_25_mean
    # - p_26_mean
    # - p_27_mean
    # - p_28_mean
    # - p_29_mean
    # - p_30_mean
    # - p_31_mean
    # - p_33_mean
    - AU01_r_var
    - AU04_r_var
    - AU05_r_var
    - AU06_r_var
    - AU07_r_var
    - AU09_r_var
    - AU10_r_var
    - AU12_r_var
    - AU14_r_var
    - AU15_r_var
    - AU17_r_var
    - AU20_r_var
    - AU23_r_var
    - AU25_r_var
    - AU26_r_var
    - AU45_r_var
    - gaze_0_x_var
    - gaze_0_y_var
    - gaze_0_z_var
    - pose_Tx_var
    - pose_Ty_var
    - pose_Tz_var
    - pose_Rz_var
    - x_1_var
    - x_8_var
    - x_21_var
    - x_22_var
    - x_38_var
    - x_43_var
    - x_48_var
    - x_57_var
    - x_51_var
    - x_54_var
    - x_60_var
    - x_62_var
    - x_66_var
    - y_1_var
    - y_8_var
    - y_21_var
    - y_22_var
    - y_38_var
    - y_43_var
    - y_48_var
    - y_57_var
    - y_51_var
    - y_54_var
    - y_60_var
    - y_62_var
    - y_66_var
    # - p_0_var
    # - p_1_var
    # - p_2_var
    # - p_3_var
    # - p_4_var
    # - p_5_var
    # - p_6_var
    # - p_7_var
    # - p_8_var
    # - p_9_var
    # - p_10_var
    # - p_11_var
    # - p_12_var
    # - p_13_var
    # - p_14_var
    # - p_15_var
    # - p_16_var
    # - p_17_var
    # - p_18_var
    # - p_19_var
    # - p_20_var
    # - p_21_var
    # - p_22_var
    # - p_23_var
    # - p_24_var
    # - p_25_var
    # - p_26_var
    # - p_27_var
    # - p_28_var
    # - p_29_var
    # - p_30_var
    # - p_31_var
    # - p_32_var
    # - p_33_var
    - AU04_c
    - AU05_c
    - AU06_c
    - AU07_c
    - AU09_c
    - AU10_c
    - AU12_c
    - AU14_c
    - AU15_c
    - AU17_c
    - AU23_c
    - AU26_c
    - AU28_c
    - AU45_c

  closing_window: 6
