binary_features:

integer_features:

float_features:
  - MFCC_0
  - MFCC_1
  - MFCC_2
  - MFCC_3
  - MFCC_4
  - MFCC_5
  - MFCC_6
  - MFCC_7
  - MFCC_8
  - MFCC_9
  - MFCC_10
  - MFCC_11
  - MFCC_12
  - MFCC_13
  - MFCC_14
  - MFCC_15
  - MFCC_16
  - MFCC_17
  - MFCC_18
  - MFCC_19
  - Chroma_0
  - Chroma_1
  - Chroma_2
  - Chroma_3
  - Chroma_4
  - Chroma_5
  - Chroma_6
  - Chroma_7
  - Chroma_8
  - Chroma_9
  - Chroma_10
  - Chroma_11
  - Mel_Spect_0
  - Mel_Spect_1
  - Mel_Spect_2
  - Mel_Spect_3
  - Mel_Spect_4
  - Mel_Spect_5
  - Mel_Spect_6
  - Mel_Spect_7
  - Mel_Spect_8
  - Mel_Spect_9
  - Mel_Spect_10
  - Mel_Spect_11
  - Mel_Spect_12
  - Mel_Spect_13
  - Mel_Spect_14
  - Mel_Spect_15
  - Mel_Spect_16
  - Mel_Spect_17
  - Mel_Spect_18
  - Mel_Spect_19
  - Mel_Spect_20
  - Mel_Spect_21
  - Mel_Spect_22
  - Mel_Spect_23
  - Mel_Spect_24
  - Mel_Spect_25
  - Mel_Spect_26
  - Mel_Spect_27
  - Mel_Spect_28
  - Mel_Spect_29
  - Mel_Spect_30
  - Mel_Spect_31
  - Mel_Spect_32
  - Mel_Spect_33
  - Mel_Spect_34
  - Mel_Spect_35
  - Mel_Spect_36
  - Mel_Spect_37
  - Mel_Spect_38
  - Mel_Spect_39
  - Mel_Spect_40
  - Mel_Spect_41
  - Mel_Spect_42
  - Mel_Spect_43
  - Mel_Spect_44
  - Mel_Spect_45
  - Mel_Spect_46
  - Mel_Spect_47
  - Mel_Spect_48
  - Mel_Spect_49
  - Mel_Spect_50
  - Mel_Spect_51
  - Mel_Spect_52
  - Mel_Spect_53
  - Mel_Spect_54
  - Mel_Spect_55
  - Mel_Spect_56
  - Mel_Spect_57
  - Mel_Spect_58
  - Mel_Spect_59
  - Mel_Spect_60
  - Mel_Spect_61
  - Mel_Spect_62
  - Mel_Spect_63
  - Mel_Spect_64
  - Mel_Spect_65
  - Mel_Spect_66
  - Mel_Spect_67
  - Mel_Spect_68
  - Mel_Spect_69
  - Mel_Spect_70
  - Mel_Spect_71
  - Mel_Spect_72
  - Mel_Spect_73
  - Mel_Spect_74
  - Mel_Spect_75
  - Mel_Spect_76
  - Mel_Spect_77
  - Mel_Spect_78
  - Mel_Spect_79
  - Mel_Spect_80
  - Mel_Spect_81
  - Mel_Spect_82
  - Mel_Spect_83
  - Mel_Spect_84
  - Mel_Spect_85
  - Mel_Spect_86
  - Mel_Spect_87
  - Mel_Spect_88
  - Mel_Spect_89
  - Mel_Spect_90
  - Mel_Spect_91
  - Mel_Spect_92
  - Mel_Spect_93
  - Mel_Spect_94
  - Mel_Spect_95
  - Mel_Spect_96
  - Mel_Spect_97
  - Mel_Spect_98
  - Mel_Spect_99
  - Mel_Spect_100
  - Mel_Spect_101
  - Mel_Spect_102
  - Mel_Spect_103
  - Mel_Spect_104
  - Mel_Spect_105
  - Mel_Spect_106
  - Mel_Spect_107
  - Mel_Spect_108
  - Mel_Spect_109
  - Mel_Spect_110
  - Mel_Spect_111
  - Mel_Spect_112
  - Mel_Spect_113
  - Mel_Spect_114
  - Mel_Spect_115
  - Mel_Spect_116
  - Mel_Spect_117
  - Mel_Spect_118
  - Mel_Spect_119
  - Mel_Spect_120
  - Mel_Spect_121
  - Mel_Spect_122
  - Mel_Spect_123
  - Mel_Spect_124
  - Mel_Spect_125
  - Mel_Spect_126
  - Mel_Spect_127
  - Spect_Contrast_0
  - Spect_Contrast_1
  - Spect_Contrast_2
  - Spect_Contrast_3
  - Spect_Contrast_4
  - Spect_Contrast_5
  - Spect_Contrast_6
  - Rolloff_0
