mean_features:
  - MFCC_0
  - MFCC_1
  - MFCC_2
  - MFCC_3
  - MFCC_4
  - MFCC_5
  - MFCC_6
  - MFCC_7
  - MFCC_8
  - MFCC_9
  - MFCC_10
  - MFCC_11
  - MFCC_12
  - MFCC_13
  - MFCC_14
  - MFCC_15
  - MFCC_16
  - MFCC_17
  - MFCC_18
  - MFCC_19
  - Chroma_0
  - Chroma_2
  - Chroma_4
  - Chroma_5
  - Chroma_6
  - Chroma_8
  - Chroma_10
  - Chroma_11
  - Mel_Spect_0
  - Mel_Spect_2
  - Mel_Spect_4
  - Mel_Spect_5
  - Mel_Spect_97
  - Mel_Spect_109
  - Mel_Spect_127
  - Spect_Contrast_0
  - Spect_Contrast_1
  - Spect_Contrast_2
  - Spect_Contrast_3
  - Spect_Contrast_4
  - Spect_Contrast_5
  - Spect_Contrast_6
  - Rolloff_0
  - gaze_0_x
  - gaze_0_y
  - gaze_0_z
  - pose_Tx
  - pose_Ty
  - pose_Ry
  - pose_Rz
  - p_scale
  - x_1
  - x_8
  - x_15
  - x_21
  - x_22
  - x_48
  - x_54
  - x_62
  - x_66
  - y_1
  - y_8
  - y_15
  - y_21
  - y_22
  - y_48
  - y_54
  - y_62
  - y_66

variance_features:
  - MFCC_0
  - MFCC_1
  - MFCC_2
  - MFCC_3
  - MFCC_4
  - MFCC_5
  - MFCC_6
  - MFCC_7
  - MFCC_8
  - MFCC_9
  - MFCC_10
  - MFCC_11
  - MFCC_12
  - MFCC_13
  - MFCC_14
  - MFCC_15
  - MFCC_16
  - MFCC_17
  - MFCC_18
  - MFCC_19
  - Chroma_0
  - Chroma_2
  - Chroma_4
  - Chroma_5
  - Chroma_6
  - Chroma_8
  - Chroma_10
  - Chroma_11
  - Mel_Spect_0
  - Mel_Spect_2
  - Mel_Spect_4
  - Mel_Spect_5
  - Mel_Spect_97
  - Mel_Spect_109
  - Mel_Spect_127
  - Spect_Contrast_0
  - Spect_Contrast_1
  - Spect_Contrast_2
  - Spect_Contrast_3
  - Spect_Contrast_4
  - Spect_Contrast_5
  - Spect_Contrast_6
  - Rolloff_0
  - gaze_0_x
  - gaze_0_y
  - gaze_0_z
  - pose_Tx
  - pose_Ty
  - pose_Ry
  - pose_Rz
  - p_scale
  - x_1
  - x_8
  - x_15
  - x_21
  - x_22
  - x_48
  - x_54
  - x_62
  - x_66
  - y_1
  - y_8
  - y_15
  - y_21
  - y_22
  - y_48
  - y_54
  - y_62
  - y_66

median_features:
mode_features:

max_features:
