# The directory pattern specifies the configuration for creating
# a list of directories. This allows the directories to match either
# the windows or mac/linux file structure.
# Think of the dir_pattern as a list path that can have variable names.
dir_pattern:
  - /
  - media
  - chris
  - M2
  - 4-Annotations
  - Turns
  - dir1

# The substitutes match items in the dir_pattern and are replaced
# in a combinatorial fashion
substitutes:
  dir1:
    - 1
    - 2
    - 3
    # - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
