feature_sets:
  - Syncnet-Conf
  - Gaze-Radians
  - Annotation-Speaker

feature_files:
  Syncnet-Conf:
    dir_pattern:
      - /
      - media
      - chris
      - M2
      - 2-Processed_Data
      - syncnet_output
      - pywork
      - num
      - framewise_confidences.csv
    substitutes:
      num:
        - 1
  Gaze-Radians:
    dir_pattern:
      - /
      - media
      - chris
      - M2
      - 2-Processed_Data
      - Gaze-Data
      - num
      - pose_ang.csv
    substitutes:
      num:
        - 1
  Annotation-Speaker:
    dir_pattern:
      - /
      - home
      - chris
      - coding
      - usc
      - modeling-pipeline
      - data
      - va_output
      - num
      - speaking.csv
    substitutes:
      num:
        - 1

features:
  Annotation-Speaker:
    - speaking
  Syncnet-Conf:
    - Confidence
  Audio-Opensmile:
    - F0semitoneFrom27.5Hz_sma3nz
    - jitterLocal_sma3nz
    - shimmerLocaldB_sma3nz
    - HNRdBACF_sma3nz
    - logRelF0-H1-H2_sma3nz
    - logRelF0-H1-A3_sma3nz
    - F1frequency_sma3nz
    - F1bandwidth_sma3nz
