dir_pattern:
  - /
  - media
  - chris
  - M2
  - 1-Raw_Data
  - Videos
  - num
  - cropped
  - video

substitutes:
  num:
    - 1
    - 2
    - 3
    # - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
  video:
    - left.mp4
    - right.mp4
    - center.mp4
    - group.mp4