mean_features:
  - ALMFCC_0
  - ALMFCC_1
  - ALMFCC_2
  - ALMFCC_3
  - ALMFCC_4
  - ALMFCC_5
  - ALMFCC_6
  - ALMFCC_7
  - ALMFCC_8
  - ALMFCC_9
  - ALMFCC_10
  - ALMFCC_11
  - ALMFCC_12
  - ALMFCC_13
  - ALMFCC_14
  - ALMFCC_15
  - ALMFCC_16
  - ALMFCC_17
  - ALMFCC_18
  - ALMFCC_19
  - ALChroma_0
  - ALChroma_2
  - ALChroma_4
  - ALChroma_5
  - ALChroma_6
  - ALChroma_8
  - ALChroma_10
  - ALChroma_11
  - ALMel_Spect_0
  - ALMel_Spect_2
  - ALMel_Spect_4
  - ALMel_Spect_5
  - ALMel_Spect_97
  - ALMel_Spect_109
  - ALMel_Spect_127
  - ALSpect_Contrast_0
  - ALSpect_Contrast_1
  - ALSpect_Contrast_2
  - ALSpect_Contrast_3
  - ALSpect_Contrast_4
  - ALSpect_Contrast_5
  - ALSpect_Contrast_6
  - ALRolloff_0
  - VOLgaze_0_x
  - VOLgaze_0_y
  - VOLgaze_0_z
  - VOLpose_Tx
  - VOLpose_Ty
  - VOLpose_Ry
  - VOLpose_Rz
  - VOLp_scale
  - VOLx_1
  - VOLx_8
  - VOLx_15
  - VOLx_21
  - VOLx_22
  - VOLx_48
  - VOLx_54
  - VOLx_62
  - VOLx_66
  - VOLy_1
  - VOLy_8
  - VOLy_15
  - VOLy_21
  - VOLy_22
  - VOLy_48
  - VOLy_54
  - VOLy_62
  - VOLy_66
  - VORgaze_0_x
  - VORgaze_0_y
  - VORgaze_0_z
  - VORpose_Tx
  - VORpose_Ty
  - VORpose_Ry
  - VORpose_Rz
  - VORp_scale
  - VORx_1
  - VORx_8
  - VORx_15
  - VORx_21
  - VORx_22
  - VORx_48
  - VORx_54
  - VORx_62
  - VORx_66
  - VORy_1
  - VORy_8
  - VORy_15
  - VORy_21
  - VORy_22
  - VORy_48
  - VORy_54
  - VORy_62
  - VORy_66
  - VOCgaze_0_x
  - VOCgaze_0_y
  - VOCgaze_0_z
  - VOCpose_Tx
  - VOCpose_Ty
  - VOCpose_Ry
  - VOCpose_Rz
  - VOCp_scale
  - VOCx_1
  - VOCx_8
  - VOCx_15
  - VOCx_21
  - VOCx_22
  - VOCx_48
  - VOCx_54
  - VOCx_62
  - VOCx_66
  - VOCy_1
  - VOCy_8
  - VOCy_15
  - VOCy_21
  - VOCy_22
  - VOCy_48
  - VOCy_54
  - VOCy_62
  - VOCy_66
variance_features:
  - ALMFCC_0
  - ALMFCC_1
  - ALMFCC_2
  - ALMFCC_3
  - ALMFCC_4
  - ALMFCC_5
  - ALMFCC_6
  - ALMFCC_7
  - ALMFCC_8
  - ALMFCC_9
  - ALMFCC_10
  - ALMFCC_11
  - ALMFCC_12
  - ALMFCC_13
  - ALMFCC_14
  - ALMFCC_15
  - ALMFCC_16
  - ALMFCC_17
  - ALMFCC_18
  - ALMFCC_19
  - ALChroma_0
  - ALChroma_2
  - ALChroma_4
  - ALChroma_5
  - ALChroma_6
  - ALChroma_8
  - ALChroma_10
  - ALChroma_11
  - ALMel_Spect_0
  - ALMel_Spect_2
  - ALMel_Spect_4
  - ALMel_Spect_5
  - ALMel_Spect_97
  - ALMel_Spect_109
  - ALMel_Spect_127
  - ALSpect_Contrast_0
  - ALSpect_Contrast_1
  - ALSpect_Contrast_2
  - ALSpect_Contrast_3
  - ALSpect_Contrast_4
  - ALSpect_Contrast_5
  - ALSpect_Contrast_6
  - ALRolloff_0
  - VOLgaze_0_x
  - VOLgaze_0_y
  - VOLgaze_0_z
  - VOLpose_Tx
  - VOLpose_Ty
  - VOLpose_Ry
  - VOLpose_Rz
  - VOLp_scale
  - VOLx_1
  - VOLx_8
  - VOLx_15
  - VOLx_21
  - VOLx_22
  - VOLx_48
  - VOLx_54
  - VOLx_62
  - VOLx_66
  - VOLy_1
  - VOLy_8
  - VOLy_15
  - VOLy_21
  - VOLy_22
  - VOLy_48
  - VOLy_54
  - VOLy_62
  - VOLy_66
  - VORgaze_0_x
  - VORgaze_0_y
  - VORgaze_0_z
  - VORpose_Tx
  - VORpose_Ty
  - VORpose_Ry
  - VORpose_Rz
  - VORp_scale
  - VORx_1
  - VORx_8
  - VORx_15
  - VORx_21
  - VORx_22
  - VORx_48
  - VORx_54
  - VORx_62
  - VORx_66
  - VORy_1
  - VORy_8
  - VORy_15
  - VORy_21
  - VORy_22
  - VORy_48
  - VORy_54
  - VORy_62
  - VORy_66
  - VOCgaze_0_x
  - VOCgaze_0_y
  - VOCgaze_0_z
  - VOCpose_Tx
  - VOCpose_Ty
  - VOCpose_Ry
  - VOCpose_Rz
  - VOCp_scale
  - VOCx_1
  - VOCx_8
  - VOCx_15
  - VOCx_21
  - VOCx_22
  - VOCx_48
  - VOCx_54
  - VOCx_62
  - VOCx_66
  - VOCy_1
  - VOCy_8
  - VOCy_15
  - VOCy_21
  - VOCy_22
  - VOCy_48
  - VOCy_54
  - VOCy_62
  - VOCy_66
median_features:
mode_features:
max_features:
