data_dir: /media/chris/M2/2-Processed_Data/

feature_sets:
  - Audio-Librosa
  - Video-OpenFace
  - Annotation-Turns

sessions:
  - 1
  - 2
  - 3
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  # - 14
  - 15
  - 16
  - 17
  # - 18
  # - 19
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27

positions:
  - left
  - right
  - center

feature_files:
  Audio-Librosa:
    - audio_features.csv
  Video-OpenFace:
    - left.csv
    - center.csv
    - right.csv
  Annotation-Turns:
    - turns.csv

features:
  Audio-Librosa:
    - MFCC_0
    - MFCC_1
    - MFCC_2
    - MFCC_3
    # - MFCC_4
    # - MFCC_5
    # - MFCC_6
    # - MFCC_7
    # - MFCC_8
    # - MFCC_9
    # - MFCC_10
    # - MFCC_11
    # - MFCC_12
    # - MFCC_13
    # - MFCC_14
    # - MFCC_15
    # - MFCC_16
    # - MFCC_17
    # - MFCC_18
    # - MFCC_19
    - Chroma_0
    - Chroma_1
    - Chroma_2
    - Chroma_3
    - Chroma_4
    - Chroma_5
    - Chroma_6
    - Chroma_7
    - Chroma_8
    - Chroma_9
    - Chroma_10
    - Chroma_11
    - Mel_Spect_0
    - Mel_Spect_1
    - Mel_Spect_2
    - Mel_Spect_3
    - Mel_Spect_4
    - Mel_Spect_5
    - Mel_Spect_6
    - Mel_Spect_7
    - Mel_Spect_8
    - Mel_Spect_9
    - Mel_Spect_10
    - Mel_Spect_11
    - Mel_Spect_12
    - Mel_Spect_13
    - Mel_Spect_14
    - Mel_Spect_15
    - Mel_Spect_16
    - Mel_Spect_17
    - Mel_Spect_18
    - Mel_Spect_19
    - Mel_Spect_20
    - Mel_Spect_21
    - Mel_Spect_22
    - Mel_Spect_23
    - Mel_Spect_24
    - Mel_Spect_25
    - Mel_Spect_26
    - Mel_Spect_27
    - Mel_Spect_28
    - Mel_Spect_29
    - Mel_Spect_30
    - Mel_Spect_31
    - Mel_Spect_32
    - Mel_Spect_33
    - Mel_Spect_34
    - Mel_Spect_35
    - Mel_Spect_36
    - Mel_Spect_37
    - Mel_Spect_38
    - Mel_Spect_39
    - Mel_Spect_40
    - Mel_Spect_41
    - Mel_Spect_42
    - Mel_Spect_43
    - Mel_Spect_44
    - Mel_Spect_45
    - Mel_Spect_46
    - Mel_Spect_47
    - Mel_Spect_48
    - Mel_Spect_49
    - Mel_Spect_50
    # - Mel_Spect_51
    # - Mel_Spect_52
    # - Mel_Spect_53
    # - Mel_Spect_54
    # - Mel_Spect_55
    # - Mel_Spect_56
    # - Mel_Spect_57
    # - Mel_Spect_58
    # - Mel_Spect_59
    # - Mel_Spect_60
    # - Mel_Spect_61
    # - Mel_Spect_62
    # - Mel_Spect_63
    # - Mel_Spect_64
    # - Mel_Spect_65
    # - Mel_Spect_66
    # - Mel_Spect_67
    # - Mel_Spect_68
    # - Mel_Spect_69
    # - Mel_Spect_70
    # - Mel_Spect_71
    # - Mel_Spect_72
    # - Mel_Spect_73
    # - Mel_Spect_74
    # - Mel_Spect_75
    # - Mel_Spect_76
    # - Mel_Spect_77
    # - Mel_Spect_78
    # - Mel_Spect_79
    # - Mel_Spect_80
    # - Mel_Spect_81
    # - Mel_Spect_82
    # - Mel_Spect_83
    # - Mel_Spect_84
    # - Mel_Spect_85
    # - Mel_Spect_86
    # - Mel_Spect_87
    # - Mel_Spect_88
    # - Mel_Spect_89
    # - Mel_Spect_90
    # - Mel_Spect_91
    # - Mel_Spect_92
    # - Mel_Spect_93
    # - Mel_Spect_94
    # - Mel_Spect_95
    # - Mel_Spect_96
    # - Mel_Spect_97
    # - Mel_Spect_98
    # - Mel_Spect_99
    # - Mel_Spect_100
    # - Mel_Spect_101
    # - Mel_Spect_102
    # - Mel_Spect_103
    # - Mel_Spect_104
    # - Mel_Spect_105
    # - Mel_Spect_106
    # - Mel_Spect_107
    # - Mel_Spect_108
    # - Mel_Spect_109
    # - Mel_Spect_110
    # - Mel_Spect_111
    # - Mel_Spect_112
    # - Mel_Spect_113
    # - Mel_Spect_114
    # - Mel_Spect_115
    # - Mel_Spect_116
    # - Mel_Spect_117
    # - Mel_Spect_118
    # - Mel_Spect_119
    # - Mel_Spect_120
    # - Mel_Spect_121
    # - Mel_Spect_122
    # - Mel_Spect_123
    # - Mel_Spect_124
    # - Mel_Spect_125
    # - Mel_Spect_126
    # - Mel_Spect_127
    - Spect_Contrast_0
    - Spect_Contrast_1
    - Spect_Contrast_2
    - Spect_Contrast_3
    - Spect_Contrast_4
    - Spect_Contrast_5
    - Spect_Contrast_6
    - Rolloff_0

  # https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format
  Video-OpenFace:
    # - frame
    - confidence
    # - gaze_0_x
    # - gaze_0_y
    # - gaze_0_z
    # - gaze_1_x
    # - gaze_1_y
    # - gaze_1_z
    - gaze_angle_x
    - gaze_angle_y
    - pose_Tx
    - pose_Ty
    - pose_Tz
    - pose_Rx
    - pose_Ry
    - pose_Rz
    # - x_0
    # - x_1
    - x_2
    # - x_3
    # - x_4
    # - x_5
    # - x_6
    # - x_7
    - x_8
    # - x_9
    # - x_10
    # - x_11
    # - x_12
    # - x_13
    - x_14
    # - x_15
    # - x_16
    # - x_17
    # - x_18
    - x_19
    # - x_20
    - x_21
    - x_22
    # - x_23
    - x_24
    # - x_25
    # - x_26
    # - x_27
    # - x_28
    # - x_29
    - x_30
    # - x_31
    # - x_32
    - x_33
    # - x_34
    # - x_35
    - x_36
    - x_37
    - x_38
    - x_39
    - x_40
    - x_41
    - x_42
    - x_43
    - x_44
    - x_45
    - x_46
    - x_47
    - x_48
    - x_49
    - x_50
    - x_51
    - x_52
    - x_53
    - x_54
    - x_55
    - x_56
    - x_57
    - x_58
    - x_59
    - x_60
    - x_61
    - x_62
    - x_63
    - x_64
    - x_65
    - x_66
    - x_67
    # - y_0
    # - y_1
    - y_2
    # - y_3
    # - y_4
    # - y_5
    # - y_6
    # - y_7
    - y_8
    # - y_9
    # - y_10
    # - y_11
    # - y_12
    # - y_13
    - y_14
    # - y_15
    # - y_16
    # - y_17
    # - y_18
    - y_19
    # - y_20
    - y_21
    - y_22
    # - y_23
    - y_24
    # - y_25
    # - y_26
    # - y_27
    # - y_28
    # - y_29
    - y_30
    # - y_31
    # - y_32
    - y_33
    # - y_34
    # - y_35
    - y_36
    - y_37
    - y_38
    - y_39
    - y_40
    - y_41
    - y_42
    - y_43
    - y_44
    - y_45
    - y_46
    - y_47
    - y_48
    - y_49
    - y_50
    - y_51
    - y_52
    - y_53
    - y_54
    - y_55
    - y_56
    - y_57
    - y_58
    - y_59
    - y_60
    - y_61
    - y_62
    - y_63
    - y_64
    - y_65
    - y_66
    - y_67
    # - X_0
    # - X_1
    # - X_2
    # - X_3
    # - X_4
    # - X_5
    # - X_6
    # - X_7
    # - X_8
    # - X_9
    # - X_10
    # - X_11
    # - X_12
    # - X_13
    # - X_14
    # - X_15
    # - X_16
    # - X_17
    # - X_18
    # - X_19
    # - X_20
    # - X_21
    # - X_22
    # - X_23
    # - X_24
    # - X_25
    # - X_26
    # - X_27
    # - X_28
    # - X_29
    # - X_30
    # - X_31
    # - X_32
    # - X_33
    # - X_34
    # - X_35
    # - X_36
    # - X_37
    # - X_38
    # - X_39
    # - X_40
    # - X_41
    # - X_42
    # - X_43
    # - X_44
    # - X_45
    # - X_46
    # - X_47
    # - X_48
    # - X_49
    # - X_50
    # - X_51
    # - X_52
    # - X_53
    # - X_54
    # - X_55
    # - X_56
    # - X_57
    # - X_58
    # - X_59
    # - X_60
    # - X_61
    # - X_62
    # - X_63
    # - X_64
    # - X_65
    # - X_66
    # - X_67
    # - Y_0
    # - Y_1
    # - Y_2
    # - Y_3
    # - Y_4
    # - Y_5
    # - Y_6
    # - Y_7
    # - Y_8
    # - Y_9
    # - Y_10
    # - Y_11
    # - Y_12
    # - Y_13
    # - Y_14
    # - Y_15
    # - Y_16
    # - Y_17
    # - Y_18
    # - Y_19
    # - Y_20
    # - Y_21
    # - Y_22
    # - Y_23
    # - Y_24
    # - Y_25
    # - Y_26
    # - Y_27
    # - Y_28
    # - Y_29
    # - Y_30
    # - Y_31
    # - Y_32
    # - Y_33
    # - Y_34
    # - Y_35
    # - Y_36
    # - Y_37
    # - Y_38
    # - Y_39
    # - Y_40
    # - Y_41
    # - Y_42
    # - Y_43
    # - Y_44
    # - Y_45
    # - Y_46
    # - Y_47
    # - Y_48
    # - Y_49
    # - Y_50
    # - Y_51
    # - Y_52
    # - Y_53
    # - Y_54
    # - Y_55
    # - Y_56
    # - Y_57
    # - Y_58
    # - Y_59
    # - Y_60
    # - Y_61
    # - Y_62
    # - Y_63
    # - Y_64
    # - Y_65
    # - Y_66
    # - Y_67
    # - Z_0
    # - Z_1
    # - Z_2
    # - Z_3
    # - Z_4
    # - Z_5
    # - Z_6
    # - Z_7
    # - Z_8
    # - Z_9
    # - Z_10
    # - Z_11
    # - Z_12
    # - Z_13
    # - Z_14
    # - Z_15
    # - Z_16
    # - Z_17
    # - Z_18
    # - Z_19
    # - Z_20
    # - Z_21
    # - Z_22
    # - Z_23
    # - Z_24
    # - Z_25
    # - Z_26
    # - Z_27
    # - Z_28
    # - Z_29
    # - Z_30
    # - Z_31
    # - Z_32
    # - Z_33
    # - Z_34
    # - Z_35
    # - Z_36
    # - Z_37
    # - Z_38
    # - Z_39
    # - Z_40
    # - Z_41
    # - Z_42
    # - Z_43
    # - Z_44
    # - Z_45
    # - Z_46
    # - Z_47
    # - Z_48
    # - Z_49
    # - Z_50
    # - Z_51
    # - Z_52
    # - Z_53
    # - Z_54
    # - Z_55
    # - Z_56
    # - Z_57
    # - Z_58
    # - Z_59
    # - Z_60
    # - Z_61
    # - Z_62
    # - Z_63
    # - Z_64
    # - Z_65
    # - Z_66
    # - Z_67
    # - p_scale
    # - p_rx
    # - p_ry
    # - p_rz
    # - p_tx
    # - p_ty
    # - p_0
    # - p_1
    # - p_2
    # - p_3
    # - p_4
    # - p_5
    # - p_6
    # - p_7
    # - p_8
    # - p_9
    # - p_10
    # - p_11
    # - p_12
    # - p_13
    # - p_14
    # - p_15
    # - p_16
    # - p_17
    # - p_18
    # - p_19
    # - p_20
    # - p_21
    # - p_22
    # - p_23
    # - p_24
    # - p_25
    # - p_26
    # - p_27
    # - p_28
    # - p_29
    # - p_30
    # - p_31
    # - p_32
    # - p_33
    - AU01_r
    - AU02_r
    - AU04_r
    - AU05_r
    - AU06_r
    - AU07_r
    - AU09_r
    - AU10_r
    - AU12_r
    - AU14_r
    - AU15_r
    - AU17_r
    - AU20_r
    - AU23_r
    - AU25_r
    - AU26_r
    - AU45_r
    # - AU01_c
    # - AU02_c
    # - AU04_c
    # - AU05_c
    # - AU06_c
    # - AU07_c
    # - AU09_c
    # - AU10_c
    # - AU12_c
    # - AU14_c
    # - AU15_c
    # - AU17_c
    # - AU20_c
    # - AU23_c
    # - AU25_c
    # - AU26_c
    # - AU28_c
    # - AU45_c
    # - timestamp

  closing_window: 45
