data_dir: /media/chris/M2/2-Processed_Data/

feature_sets:
  - Audio-Librosa
  - Video-OpenFace
  - Annotation-Turns

sessions:
  - 1
  - 2
  - 3
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  # - 14
  - 15
  - 16
  - 17
  # - 18
  # - 19
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27

positions:
  - left
  - right
  - center

feature_files:
  Audio-Librosa:
    - audio_features.csv
  Video-OpenFace:
    - left.csv
    - center.csv
    - right.csv
  Annotation-Turns:
    - turns.csv

features:
  Audio-Librosa:
    - MFCC_0
    - MFCC_1
    - MFCC_2
    - MFCC_3
    - MFCC_4
    - MFCC_5
    - MFCC_6
    - MFCC_7
    - MFCC_8
    - MFCC_9
    - MFCC_10
    - MFCC_11
    - MFCC_12
    - MFCC_13
    - MFCC_14
    - MFCC_15
    - MFCC_16
    - MFCC_17
    - MFCC_18
    - MFCC_19
    - Chroma_0
    - Chroma_1
    - Chroma_2
    - Chroma_3
    - Chroma_4
    - Chroma_5
    - Chroma_6
    - Chroma_7
    - Chroma_8
    - Chroma_9
    - Chroma_10
    - Chroma_11
    - Mel_Spect_0
    - Mel_Spect_1
    - Mel_Spect_2
    - Mel_Spect_3
    - Mel_Spect_5
    - Mel_Spect_6
    - Mel_Spect_7
    - Mel_Spect_9
    - Mel_Spect_11
    - Mel_Spect_13
    - Mel_Spect_27
    - Mel_Spect_29
    - Mel_Spect_40
    - Mel_Spect_42
    - Mel_Spect_45
    - Mel_Spect_91
    - Mel_Spect_99
    - Mel_Spect_110
    - Mel_Spect_124
    - Mel_Spect_127
    - Spect_Contrast_0
    - Spect_Contrast_1
    - Spect_Contrast_2
    - Spect_Contrast_3
    - Spect_Contrast_4
    - Spect_Contrast_5
    - Spect_Contrast_6
    - Rolloff_0

  # https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format
  Video-OpenFace:
    # Custom
    - x_2
    - x_8
    - x_48
    - x_49
    - x_50
    - x_51
    - x_52
    - x_53
    - x_54
    - x_55
    - x_56
    - x_57
    - x_58
    - x_59
    - x_60
    - x_61
    - x_62
    - x_63
    - x_64
    - y_2
    - y_8
    - y_48
    - y_49
    - y_50
    - y_51
    - y_52
    - y_53
    - y_54
    - y_55
    - y_56
    - y_57
    - y_58
    - y_59
    - y_60
    - y_61
    - y_62
    - y_63
    - y_64
    # Pearson
    - gaze_0_x
    - gaze_0_y
    - gaze_0_z
    - pose_Tx
    - pose_Ty
    - pose_Tz
    - pose_Ry
    - x_0
    - y_13
    - p_scale
    - p_0
    - p_2
    - p_3
    - p_4
    - p_5
    - p_6
    - p_8
    - p_9
    - p_10
    - p_11
    - p_12
    - p_13
    - p_14
    - p_15
    - p_17
    - p_18
    - p_19
    - p_20
    - p_21
    - p_22
    - p_23
    - p_24
    - p_25
    - p_26
    - p_27
    - p_28
    - p_29
    - p_30
    - p_31
    - p_32
    - p_33
    - AU01_r
    - AU04_r
    - AU05_r
    - AU06_r
    - AU07_r
    - AU09_r
    - AU10_r
    - AU12_r
    - AU14_r
    - AU15_r
    - AU17_r
    - AU20_r
    - AU25_r
    - AU26_r
    - AU45_r
    - AU02_c
    - AU04_c
    - AU05_c
    - AU06_c
    - AU07_c
    - AU09_c
    - AU10_c
    - AU12_c
    - AU14_c
    - AU15_c
    - AU17_c
    - AU23_c
    - AU26_c
    - AU28_c
    - AU45_c

  closing_window: 45
